In [1]:
import torch

In [2]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])

In [3]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

In [4]:
z = y.expand((2,3,2,3)); z

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]],


        [[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]]])

> Multiply each column by a different number

In [5]:
o = torch.ones(1,1,1,3).float()
# print(o)
print(o.shape)
o = o*torch.tensor([[2,3,4]]).float(); o

torch.Size([1, 1, 1, 3])


tensor([[[[2., 3., 4.]]]])

In [6]:
z.float()

tensor([[[[1., 2., 3.],
          [4., 5., 6.]],

         [[1., 2., 3.],
          [4., 5., 6.]],

         [[1., 2., 3.],
          [4., 5., 6.]]],


        [[[1., 2., 3.],
          [4., 5., 6.]],

         [[1., 2., 3.],
          [4., 5., 6.]],

         [[1., 2., 3.],
          [4., 5., 6.]]]])

In [7]:
z.float()*o

tensor([[[[ 2.,  6., 12.],
          [ 8., 15., 24.]],

         [[ 2.,  6., 12.],
          [ 8., 15., 24.]],

         [[ 2.,  6., 12.],
          [ 8., 15., 24.]]],


        [[[ 2.,  6., 12.],
          [ 8., 15., 24.]],

         [[ 2.,  6., 12.],
          [ 8., 15., 24.]],

         [[ 2.,  6., 12.],
          [ 8., 15., 24.]]]])

In [8]:
z.shape

torch.Size([2, 3, 2, 3])

> Multiply each set of matrices (dim 0) by a different number

In [9]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]],


        [[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]]])

In [10]:
t =torch.tensor([[1],[2]]).float().unsqueeze(-1).unsqueeze(-1)
t,t.shape

(tensor([[[[1.]]],
 
 
         [[[2.]]]]), torch.Size([2, 1, 1, 1]))

In [11]:
z.shape,z.float()*t

(torch.Size([2, 3, 2, 3]), tensor([[[[ 1.,  2.,  3.],
           [ 4.,  5.,  6.]],
 
          [[ 1.,  2.,  3.],
           [ 4.,  5.,  6.]],
 
          [[ 1.,  2.,  3.],
           [ 4.,  5.,  6.]]],
 
 
         [[[ 2.,  4.,  6.],
           [ 8., 10., 12.]],
 
          [[ 2.,  4.,  6.],
           [ 8., 10., 12.]],
 
          [[ 2.,  4.,  6.],
           [ 8., 10., 12.]]]]))

## Example 3

In [12]:
z.shape, z

(torch.Size([2, 3, 2, 3]), tensor([[[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]],
 
 
         [[[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]],
 
          [[1, 2, 3],
           [4, 5, 6]]]]))

In [14]:
z2 = z.sum((0,2,3),keepdims=True); print(z2, z2.shape)

q = torch.tensor([1,2,3])
q = q[...,None,None]; print(q.shape)

print(z2*q)

tensor([[[[42]],

         [[42]],

         [[42]]]]) torch.Size([1, 3, 1, 1])
torch.Size([3, 1, 1])
tensor([[[[ 42]],

         [[ 84]],

         [[126]]]])
