## [TDS Article](https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be)

Basic Dim

In [7]:
import torch

In [8]:
x = torch.tensor([1, 2, 3])

In [9]:
torch.sum(x)

tensor(6)

2D tensors

In [10]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])

In [6]:
x.shape

torch.Size([2, 3])

In [12]:
torch.sum(x)

tensor(21)

In [13]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [50]:
torch.sum(x, dim=1)

tensor([ 6, 15])

The way to understand the “axis” of numpy sum is that it collapses the specified axis. So when it collapses the axis 0 (the row), it becomes just one row (it sums column-wise).

> 2 dimensions

In [14]:
y = torch.tensor([
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ],
     [
       [1, 2, 3],
       [4, 5, 6]
     ]
   ])

In [19]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [15]:
y.shape

torch.Size([3, 2, 3])

> The first dimension is collapsed by taking the sum over each of the 2D tensors

In [16]:
y.sum(dim=0) #2,3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [18]:
y.sum(dim=1) #3,3

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

In [20]:
y.sum(dim=2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

> Multiple Dimensions
* Dimensions are collapsed in order (always ascending)

In [23]:
y.sum(dim=(0)) # 1,3

tensor([[ 3,  6,  9],
        [12, 15, 18]])

In [22]:
y.sum(dim=(0,1)) # 1,3

tensor([15, 21, 27])

* Collapses occur in ascending order no matter how you enter them

In [28]:
y.sum(dim=(1,0)) # 1,3

tensor([15, 21, 27])

In [24]:
y.sum(dim=(0,2)) # 1,2

tensor([18, 45])

Keepdims sets the dimension to 1 after that dimension is collapsed

In [26]:
y.sum(dim=(0,2),keepdims=True) # 1,2

tensor([[[18],
         [45]]])

* without a mention of dimensions, all dimensions are operated over

In [29]:
y.sum(dim=(0,1,2))

tensor(63)

In [30]:
y.sum()

tensor(63)

## 4D

In [40]:
z = y.expand((2,3,2,3)); z

tensor([[[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]],


        [[[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]],

         [[1, 2, 3],
          [4, 5, 6]]]])

In [41]:
z.shape

torch.Size([2, 3, 2, 3])

In [42]:
z.sum(dim=0)

tensor([[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 2,  4,  6],
         [ 8, 10, 12]],

        [[ 2,  4,  6],
         [ 8, 10, 12]]])

In [53]:
z.sum(dim=(1,2,3))

tensor([63, 63])

In [49]:
y.numel(), z.numel()

(18, 36)