- https://rockt.github.io/2018/04/30/einsum
- https://www.youtube.com/watch?v=pkVwUVEHmfI

In [2]:
import torch
import numpy as np

In [20]:
A = torch.randint(5,(4,4)); A

tensor([[3, 0, 4, 2],
        [4, 2, 0, 2],
        [2, 2, 0, 1],
        [4, 3, 3, 1]])

In [23]:
# diagnol
torch.einsum("ii->i",A)

tensor([3, 2, 0, 1])

In [31]:
# transpose
torch.einsum("ji",A) # ji is looked at in alphabeticl order so einsum knows that j dimension should be returned first

tensor([[3, 4, 2, 4],
        [0, 2, 2, 3],
        [4, 0, 0, 3],
        [2, 2, 1, 1]])

In [32]:
torch.einsum("jj->j",A)

tensor([3, 2, 0, 1])