In [2]:
import torch
x = torch.tensor([0,1,2,3,4,5,6,7,8,9,10])
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
torch.cumsum(x,0)

tensor([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

add() with multiple args leads to the args being multiplied
https://www.youtube.com/watch?v=hPQKzsjTyyQ&t=4678s

In [3]:
x.add(2,3)

tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [4]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

https://pytorch.org/docs/stable/torch.html#torch.addcmul

In [5]:
x.addcmul(1,x,x) # x + 1*x*x (args 1 and 2 must be tensors)

tensor([  0,   2,   6,  12,  20,  30,  42,  56,  72,  90, 110])

In [8]:
x.addcdiv(1,x,torch.ones(len(x)).long()) # x + 1*x/ones (args 1 and 2 must be tensors)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

### Nonzero

In [80]:
x = torch.tensor([True,False,True,False,False,True,True,False, True])

In [82]:
x = torch.tensor([False, False,  True])

In [84]:
x.nonzero()

tensor([[2]])

# Tensor Generation

https://youtu.be/hPQKzsjTyyQ?t=5006

In [13]:
torch.randn(10) # randomly generate 10 normally distributed numbers

tensor([-2.1877,  0.3655,  1.5966, -0.5149,  0.2468, -0.3471,  0.4473, -0.3286,
        -1.8841, -0.1181])

In [3]:
torch.zeros_like(x)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
torch.linspace(-4,4,20) # output 20 numbers evenly spaced between -4 and 4 (both start and end are inclusive)

tensor([-4.0000, -3.5789, -3.1579, -2.7368, -2.3158, -1.8947, -1.4737, -1.0526,
        -0.6316, -0.2105,  0.2105,  0.6316,  1.0526,  1.4737,  1.8947,  2.3158,
         2.7368,  3.1579,  3.5789,  4.0000])