In [1]:
import torch

In [41]:
x = torch.tensor([[1.,2,3,4],
                [5,6,7,8]])

In [47]:
x.shape,x

(torch.Size([2, 4]),
 tensor([[ 1.0000e+00,  8.0000e+00,  1.0000e+02, -1.0000e+01],
         [ 5.0000e+00,  6.0000e+10,  7.0000e+00,  8.0000e+00]]))

In [89]:
x = torch.tensor([[1.,8,100,-10],
                [5,600000,7,8]])

In [90]:
x

tensor([[ 1.0000e+00,  8.0000e+00,  1.0000e+02, -1.0000e+01],
        [ 5.0000e+00,  6.0000e+05,  7.0000e+00,  8.0000e+00]])

In [91]:
m = x.mean(); m

tensor(75014.8750)

tensor(75014.8750)
tensor([[ 1.0000e+00,  8.0000e+00,  1.0000e+02, -1.0000e+01],
        [ 5.0000e+00,  6.0000e+05,  7.0000e+00,  8.0000e+00]])
tensor(0.)
tensor([[-75013.8750, -75006.8750, -74914.8750, -75024.8750],
        [-75009.8750, 524985.1250, -75007.8750, -75006.8750]])


In [67]:
(x-x.mean())

tensor([[-7.5000e+09, -7.5000e+09, -7.5000e+09, -7.5000e+09],
        [-7.5000e+09,  5.2500e+10, -7.5000e+09, -7.5000e+09]])

In [50]:
((x-x.mean())).mean()

tensor(-256.)

In [82]:
y = torch.tensor([[-7500014., -7500007., -7499915., -7500025.],
        [-7500010., 52499984., -7500008., -7500007.]])